[project]
name = "airflow-kubernetes"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.7",
]

[dependency-groups]
venv-needed = [
    "apache-airflow>=3.0.6",
    "apache-airflow-providers-cncf-kubernetes>=10.7.0",
]
